// src/lib/tournament/GroupInfo.svelte
<script lang="ts">
    import {onDestroy} from 'svelte'
    import {writable} from 'svelte/store'
    import {toStore} from '$lib/tournament'
    import {getMatchesOf, calcInfo} from '$lib/groups'

    export let groups: Groups
    export let contestants: Contestants
    export let matches: Matches
    export let state: State
    export let settings: Settings
    export let id: string

    const group = groups[id]
    const groupStore = toStore(group)
    const stateStore = toStore(state)
    $: ({state: groupState, winners} = $groupStore)

    const infos = writable(group.members.map(id => {
        const mmatches = getMatchesOf(group, matches, id)
        return calcInfo(mmatches, id)
    }))
    const matchStores = group.matches.map(mid => toStore(matches[mid]))
    const updateInfo = (id: string) => {
        const mmatches = getMatchesOf(group, matches, id)
        const {wins, diff} = calcInfo(mmatches, id)
        infos.update($infos => {
            const info = $infos.find(info => info.id === id)
            info.wins = wins
            info.diff = diff
            return $infos
        })
    }
    const unsubs = matchStores.map(matchStore => matchStore.subscribe(match => {
        updateInfo(match.left)
        updateInfo(match.right)
    }))

    const sortInfos = (a: GroupMemberInfo, b: GroupMemberInfo) => {
        const d = b.wins - a.wins
        if (d !== 0)
            return d
        return b.diff - a.diff
    }

    const isWinner = (winners: GroupWinners, mid: string) => {
        if (Array.isArray(winners))
            return winners.includes(mid)
        const {definite, selection} = winners
        return definite.includes(mid) || selection.includes(mid)
    }

    const isLuckyLoser = (state: State, mid: string) => {
        if (!settings.luckyLoser)
            return false
        if (Array.isArray(state.luckyLoser))
            return state.luckyLoser.includes(mid)
        return state.luckyLoser.definite.includes(mid) || state.luckyLoser.selection.includes(mid)
    }

    onDestroy(() => {
        unsubs.forEach(unsub => unsub())
    })
</script>

<section on:click class="card" class:tie={groupState === 'tie'}>
    <div class="name">{group.name}</div>
    <div class="table">
        <span class="head left">Teilnehmer</span>
        <span class="head right">Siege</span>
        <span class="head right">Diff</span>
        {#each $infos.sort(sortInfos) as {id, wins, diff} (id)}
            {@const {name} = contestants[id]}
            <div class="row" class:lucky-loser={isLuckyLoser($stateStore, id)} class:winner={isWinner(winners, id)}>
                <span class="left overflow" title={name}>{name}</span>
                <span class="right">{wins}</span>
                <span class="right">{diff}</span>
            </div>
        {/each}
    </div>
</section>

<style>
    section {
        cursor: pointer;
    }
    .overflow {
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
    }
    .name {
        margin-bottom: .3rem;
        font-weight: bold;
    }
    .table {
        width: 100%;
        display: grid;
        grid-template-columns: 1fr auto auto;
    }
    span {
        padding: .2rem .6rem;
    }
    .head {
        font-weight: normal;
        font-style: italic;
    }
    .left {
        text-align: left;
    }
    .right {
        text-align: right;
    }
    .row {
        display: contents;
    }
    .winner > span {
        color: hsl(var(--green-clr));
        background-color: hsl(var(--green-clr) / .1);
    }
    .lucky-loser > span {
        color: hsl(var(--yellow-clr));
        background-color: hsl(var(--yellow-clr) / .1);
    }
    .tie {
        border-color: hsl(var(--yellow-clr));
    }
</style>

// src/components/tournament/groups/GroupInfo.tsx
import {groups, contestants, matches, state, settings} from '@/state/tournament'
import {useState, useEffect} from 'react'
import {getMatchesOf, calcInfo, sortInfos} from '@/utils/groups'
import {subscribeKey} from 'valtio/utils'
import {useSnapshotKey} from '@/utils/valtio'

interface GroupInfoProps {
  id: App.Id,
  onSelect: (id: App.Id) => void
}

const isWinner = (winners: App.GroupWinners, id: App.Id) => {
  if (Array.isArray(winners))
    return winners.includes(id)
  const {definite, selection} = winners
  return definite.includes(id) || selection.includes(id)
}

const isLuckyLoser = (id: App.Id, luckyLoser: App.GroupWinners, phase: App.Phase) => {
  if (!settings.luckyLoser || phase === 'groups')
    return false
  if (Array.isArray(luckyLoser))
    return luckyLoser.includes(id)
  const {definite, selection} = luckyLoser
  return definite.includes(id) || selection.includes(id)
}

const GroupInfo = ({id, onSelect}: GroupInfoProps) => {
  const group = groups[id]
  const [infos, setInfos] = useState<App.GroupMemberInfo[]>(group.members.map(id => {
    const ms = getMatchesOf(group, id)
    return calcInfo(ms, id)
  }))
  const groupState = useSnapshotKey(group, 'state')
  const winners = useSnapshotKey(group, 'winners')
  const luckyLoser = useSnapshotKey(state, 'luckyLoser')
  const phase = useSnapshotKey(state, 'phase')

  useEffect(() => {
    const unsubs = group.matches.map(id => {
      const match = matches[id]
      const callback = () => {
        updateInfo(match.left)
        updateInfo(match.right)
      }
      const unsub1 = subscribeKey(match, 'leftScore', callback)
      const unsub2 = subscribeKey(match, 'rightScore', callback)
      return [unsub1, unsub2]
    }).flat()

    return () => unsubs.forEach(unsub => unsub())
  }, [])

  const updateInfo = (id: App.Id) => {
    const ms = getMatchesOf(group, id)
    const {wins, diff} = calcInfo(ms, id)
    setInfos(cur => {
      const info = cur.find(info => info.id === id)!
      info.wins = wins
      info.diff = diff
      return [...cur]
    })
  }

  infos.sort(sortInfos)

  return <div className={`card ${groupState === 'tie' ? 'border-draw' : ''}`} onClick={() => onSelect(id)}>
    <div className="font-bold">{group.name}</div>
    <div className="grid grid-cols-[1fr_auto_auto] w-full gap-2 ">
        <span className="italic text-left">Teilnehmer</span>
        <span className="italic text-right">Siege</span>
        <span className="italic text-right">Diff</span>
        {infos.map(({id, diff, wins}) => {
          const {name} = contestants[id]
          return <div key={id} className={`contents ${isWinner(winners, id) ? 'text-win' : ''} ${isLuckyLoser(id, luckyLoser, phase) ? 'text-draw' : ''}`}>
            <span className="text-left text-overflow" title={name}>{name}</span>
            <span className="text-right">{wins}</span>
            <span className="text-right">{diff}</span>
          </div>
        })}
    </div>
  </div>
}

export default GroupInfo
