// src/components/tournament/groups/GroupMatch.tsx
import MatchName from '../MatchName'
import {contestants} from '@/state/tournament'
import {PlaySVG, PauseSVG, PinSVG, CheckmarkSVG} from '@/components/svg'
import {useSnapshot} from 'valtio'
import {selectedMatch} from '@/state/matches'

interface GroupMatchProps {
  match: App.Match,
  editable: boolean
}

const stateIcons: Partial<Record<App.MatchState, typeof PlaySVG>> = {
  running: PlaySVG,
  paused: PauseSVG,
  pinned: PinSVG,
  finished: CheckmarkSVG
}

const GroupMatch = ({match, editable}: GroupMatchProps) => {
  const mtch = useSnapshot(match)

  const leftName = contestants[match.left].name
  const rightName = contestants[match.right].name

  const Icon = stateIcons[mtch.state]

  const select = () => {
    if (editable)
      selectedMatch.id = match.id
  }

  return <div className={`contents ${editable ? 'group' : ''}`} onClick={select}>
    <MatchName
      name={leftName}
      side="left"
      won={(a, b) => a > b}
      match={match}
      className="rounded-r-none"
    />
    <MatchName
      name={rightName}
      side="right"
      won={(a, b) => a < b}
      match={match}
      className="rounded-l-none"
    />
    <div>
      {Icon && <Icon/>}
    </div>
  </div>
}

export default GroupMatch

// src/lib/tournament/GroupMatch.svelte
<script lang="ts">
    import {selectedMatch} from '$lib/matches'
    import {toStore} from '$lib/tournament'
    import GroupMatchName from '$lib/tournament/GroupMatchName.svelte'

    import Play from '$lib/svg/Play.svelte'
    import Pause from '$lib/svg/Pause.svelte'
    import Pin from '$lib/svg/Pin.svelte'
    import Check from '$lib/svg/Check.svelte'

    export let match: Match
    export let contestants: Contestants
    export let editable: boolean

    const matchStore = toStore(match)
    const leftName = contestants[match.left].name
    const rightName = contestants[match.right].name

    $: state = $matchStore.state

    const select = () => {
        if (!editable)
            return
        $selectedMatch = match.id
    }

    const stateIcons = {
        running: Play,
        paused: Pause,
        pinned: Pin,
        finished: Check
    }
</script>

<section class:editable on:click={select}>
    <GroupMatchName side="left" name={leftName} won={(a, b) => a > b} {matchStore}/>
    <div class="line-wrapper">
        <div class="line"></div>
    </div>
    <GroupMatchName side="right" name={rightName} won={(a, b) => a < b} {matchStore}/>
    {#if state in stateIcons}
        <div class="svg small-svg">
            <svelte:component this={stateIcons[state]}/>
        </div>
    {:else}
        <div></div>
    {/if}
</section>

<style>
    .svg {
        align-self: center;
        justify-self: center;
    }
    section {
        display: contents;
    }
    .editable:hover {
        --bg-clr: hsl(var(--light-gray-clr));
    }
    .editable {
        cursor: pointer;
    }
    .line-wrapper {
        height: 100%;
        display: flex;
        align-items: center;
        padding: 0 .5rem;
    }
    .line {
        background-color: hsl(var(--light-gray-clr));
        height: .5rem;
        width: 100%;
        border-radius: 100vh;
    }
</style>
