// src/components/tournament/LuckyLoser.tsx
import {state, groups} from '@/state/tournament'
import {useSnapshot} from 'valtio'
import Tiebreaker from './Tiebreaker'
import {useSnapshotKey} from '@/utils/valtio'

const LuckyLoser = () => {
  const luckyLoser = useSnapshotKey(state, 'luckyLoser')
  const grps = useSnapshot(groups)

  const handleSubmit = (selection: App.Id[]) => {
    if (Array.isArray(state.luckyLoser))
      return
    state.luckyLoser.selection = selection
    if (state.phase === 'groupsFinished')
      state.phase = 'groups'
    state.phase = 'groupsFinished'
  }

  const show = Object.values(grps).reduce<boolean>((acc, group) => acc && group.state === 'finished', true)

  if (!show || Array.isArray(luckyLoser))
    return <></>

  return <Tiebreaker tiebreaker={luckyLoser as App.Tiebreaker} heading="Lucky Loser" onSubmit={handleSubmit}/>
}

export default LuckyLoser

// src/lib/tournament/LuckyLoser.svelte
<script lang="ts">
    import {toStore, toStoreKey} from '$lib/tournament'
    import Tiebreaker from '$lib/tournament/Tiebreaker.svelte'
    
    export let contestants: Contestants
    export let state: State
    export let groups: Groups

    const luckyLoserStore = toStoreKey(state, 'luckyLoser')
    const groupsStore = toStore(groups)

    const handleSubmit = (event: CustomEvent<string[]>) => {
        if (Array.isArray(state.luckyLoser))
            return
        const selection = event.detail
        state.luckyLoser.selection = selection
        state.phase = 'groupsFinished'
    }

    $: show = Object.values($groupsStore).reduce<boolean>((acc, group) => acc && group.state === 'finished', true)
</script>

{#if show && !Array.isArray($luckyLoserStore)}
    <Tiebreaker heading="LuckyLoser Tiebreaker" tiebreaker={$luckyLoserStore} {contestants} on:submit={handleSubmit}/>
{/if}
