// src/components/tournament/Matches.tsx
import RunningMatch from './RunningMatch'
import {
  finishedMatches,
  pausedMatches,
  pinnedMatches,
  runningMatches,
  selectedMatch
} from '@/state/matches'
import {useSnapshot, subscribe} from 'valtio'
import {useEffect, useState, useRef} from 'react'
import {CloseSVG} from '@/components/svg'

const Matches = () => {
  const running = useSnapshot(runningMatches)
  const paused = useSnapshot(pausedMatches)
  const pinned = useSnapshot(pinnedMatches)
  const finished = useSnapshot(finishedMatches)
  const [selected, setSelected] = useState<App.Id>()
  const highlightMap = useRef(new Map<App.Id, () => void>())

  useEffect(() => {
    return subscribe(selectedMatch, () => {
      const {id} = selectedMatch
      if (!id)
        return setSelected(id)
      const highlight = highlightMap.current.get(id)
      if (!highlight)
        return setSelected(id)
      highlight()
      setSelected(undefined)
    })
  }, [])

  return <div className="card overflow-auto">
    <h2>Spiele</h2>
    <div className="p-2"/>
    {selected &&<>
      <h3 className="text-lg italic flex items-center gap-2">
        <button onClick={() => selectedMatch.id = undefined} className="btn btn-svg text-base"><CloseSVG/></button>
        Ausgewählt
      </h3>
      <RunningMatch highlight hightlightMap={highlightMap.current} id={selected}/>
    </>}
    
    {!pinned.length || <>
      <h3 className="text-lg italic">Angepinned</h3>
      {pinned.map(id => {
        return <RunningMatch hightlightMap={highlightMap.current} key={id} id={id}/>
      })}
    </>}

    {!running.length || <>
      <h3 className="text-lg italic">Im Gange</h3>
      {running.map(id => {
        return <RunningMatch hightlightMap={highlightMap.current} key={id} id={id}/>
      })}
    </>}
    
    {!paused.length || <>
      <h3 className="text-lg italic">Pausiert</h3>
      {paused.map(id => {
        return <RunningMatch hightlightMap={highlightMap.current} key={id} id={id}/>
      })}
    </>}
    
    {!finished.length || <>
      <h3 className="text-lg italic">Beendet</h3>
      {finished.map(id => {
        return <RunningMatch hightlightMap={highlightMap.current} key={id} id={id}/>
      })}
    </>}
  </div>
}

export default Matches

// src/lib/tournament/Matches.svelte
<script lang="ts">
    import {getContext} from 'svelte'
    import {selectedMatch, groupByState} from '$lib/matches'
    import {toStore} from '$lib/tournament'
    import RunningMatch from '$lib/tournament/RunningMatch.svelte'

    const tournament = getContext<Tournament>('tournament')
    const {matches, settings, contestants} = tournament
    const matchesStore = toStore(matches)
    
    $: groupedMatches = groupByState($matchesStore)
    $: ({running, pinned, paused, finished} = groupedMatches)

    let runningMatches: RunningMatch[] = []
    let pinnedMatches: RunningMatch[] = []
    let pausedMatches: RunningMatch[] = []
    let finishedMatches: RunningMatch[] = []
    let selected: string
    const selectOrHighlight = (id: string) => {
        selected = ''
        const runningIndex = running?.findIndex(id_ => id === id_)
        if (runningIndex !== undefined && runningIndex !== -1)
            return runningMatches[runningIndex].highlight()
        const pinnedIndex = pinned?.findIndex(id_ => id === id_)
        if (pinnedIndex !== undefined && pinnedIndex !== -1)
            return pinnedMatches[pinnedIndex].highlight()
        const pausedIndex = paused?.findIndex(id_ => id === id_)
        if (pausedIndex !== undefined && pausedIndex !== -1)
            return pausedMatches[pausedIndex].highlight()
        const finishedIndex = finished?.findIndex(id_ => id === id_)
        if (finishedIndex !== undefined && finishedIndex !== -1)
            return finishedMatches[finishedIndex].highlight()
        selected = id
    }
    $: selectOrHighlight($selectedMatch)

    $: show = selected || running || pinned || paused || finished
</script>

{#if show}
    <div class="card">
        {#if selected}
            <h2>Ausgewählt</h2>
            {#key selected}
                <RunningMatch match={matches[selected]} {settings} {contestants}/>
            {/key}
        {/if}
        {#if pinned}
            <h2>Angepinned</h2>
            {#each pinned as id, index (id)}
                <RunningMatch bind:this={pinnedMatches[index]} match={matches[id]} {settings} {contestants}/>
            {/each}
        {/if}
        {#if running}
            <h2>Running</h2>
            {#each running as id, index (id)}
                <RunningMatch bind:this={runningMatches[index]} match={matches[id]} {settings} {contestants}/>
            {/each}
        {/if}
        {#if paused}
            <h2>Pausiert</h2>
            {#each paused as id, index (id)}
                <RunningMatch bind:this={pausedMatches[index]} match={matches[id]} {settings} {contestants}/>
            {/each}
        {/if}
        {#if finished}
            <h2>Beendet</h2>
            {#each finished as id, index (id)}
                <RunningMatch bind:this={finishedMatches[index]} match={matches[id]} {settings} {contestants}/>
            {/each}
        {/if}
    </div>
{/if}

<style>
    h2 {
        font-style: italic;
    }
    div {
        overflow-y: auto;
        display: flex;
        flex-direction: column;
        gap: .7rem;
        scroll-behavior: smooth;
        scroll-padding: 10rem;
    }
</style>
