// src/components/tournament/RunningMatch.tsx
import {matches, contestants, settings} from '@/state/tournament'
import {useSnapshot} from 'valtio'
import {EditableText} from '@/components/input'
import {useState, useRef, useEffect} from 'react'
import {CloseSVG, PinSVG, PauseSVG, PlaySVG} from '@/components/svg'
import {selectedMatch} from '@/state/matches'
import popupQueue from '@/state/popup'

interface RunningMatchProps {
  id: App.Id,
  hightlightMap: Map<App.Id, () => void>,
  highlight?: boolean
}

const selectAll = (event: React.FormEvent<HTMLInputElement>) => {
  event.currentTarget.select()
}

const RunningMatch = ({id, hightlightMap, highlight: _hightlight = false}: RunningMatchProps) => {
  const match = matches[id]
  const mtch = useSnapshot(match)
  const [editing, setEditing] = useState(false)
  const ref = useRef<HTMLDivElement>(null)

  const highlight = () => {
    const div = ref.current!
    div.classList.remove('running-match-highlight')
    div.getBoundingClientRect()
    div.scrollIntoView()
    div.classList.add('running-match-highlight')
  }

  useEffect(() => {
    hightlightMap.set(id, highlight)
    if (editing)
      setEditing(false)
    if (_hightlight)
      highlight()
    return () => {
      hightlightMap.delete(id)
    }
  }, [id])
  
  const leftName = contestants[match.left].name
  const rightName = contestants[match.right].name
  const {state} = mtch
  const time = mtch.time ?? settings.defaultTime

  const hours = Math.floor(time / 3600)
  const minutes = Math.floor(time / 60) - hours * 60
  const seconds = time - hours * 3600 - minutes * 60

  const saveHours = (value: string) => {
    const numeric = parseInt(value)
    const clamped = clamp(numeric, 0, 59)
    settings.defaultTime = match.time = clamped * 3600 + minutes * 60 + seconds
    return true
  }
  const saveMinutes = (value: string) => {
    const numeric = parseInt(value)
    const clamped = clamp(numeric, 0, 59)
    settings.defaultTime = match.time = hours * 3600 + clamped * 60 + seconds
    return true
  }
  const saveSeconds = (value: string) => {
    const numeric = parseInt(value)
    const clamped = clamp(numeric, 0, 59)
    settings.defaultTime = match.time = hours * 3600 + minutes * 60 + clamped
    return true
  }
  const clamp = (value: number, min: number, max: number) => {
    if (value < min) return min
    if (value > max) return max
    return value
  }
  const addZeros = (number: number) => {
    if (number >= 0 && number <= 9) return `0${number}`
    return '' + number
  }

  let leftScore = editing ? match.leftScore.toString() : ''
  let rightScore = editing ? match.rightScore.toString() : ''

  const startMatch = () => {
    if (time === 0)
      return popupQueue.push({message: 'Dauer muss größer als 0 sein', error: true})
    match.state = 'running'
    match.time = time
    selectedMatch.id = undefined
  }

  const closeMatch = () => {
    const ls = parseInt(leftScore) || 0
    const rs = parseInt(rightScore) || 0
    if (!match.drawable && ls === rs) {
      popupQueue.push({
        message: 'Es muss einenen eindeutigen Gewinner geben',
        error: true
      })
      return
    }

    match.state = 'closed'
    match.leftScore = ls
    match.rightScore = rs

    if (editing)
      setEditing(false)
  }
  
  return <div ref={ref} className={`${state === 'finished' && time === 0 ? 'text-red-500' : ''} grid grid-cols-[8ch_11ch_8ch] items-center justify-center text-2xl gap-1`}>
    <div className="text-overflow" title={leftName}>{leftName}</div>
    <div className="flex items-center justify-center gap-1">
      {state === 'waiting' || state === 'pinned'
        ? <>
          <EditableText load={() => addZeros(hours)} save={saveHours} style={{width: '1.6em', padding: '.2em'}}/> :
          <EditableText load={() => addZeros(minutes)} save={saveMinutes} style={{width: '1.6em', padding: '.2em'}}/> :
          <EditableText load={() => addZeros(seconds)} save={saveSeconds} style={{width: '1.6em', padding: '.2em'}}/>
        </>
        : <>{addZeros(hours)} : {addZeros(minutes)} : {addZeros(seconds)}</>}
    </div>
    <div className="text-overflow text-right" title={rightName}>{rightName}</div>
    {state === 'waiting' || state === 'pinned'
      ? <span className="col-span-3 flex items-center justify-center">
        {state === 'pinned'
          ? <button onClick={() => match.state = 'waiting'} className="btn btn-svg text-base"><CloseSVG/></button>
          : <button onClick={() => {
            match.state = 'pinned'
            selectedMatch.id = undefined
          }} className="btn btn-svg text-base"><PinSVG/></button>}
        <button onClick={startMatch} className="btn text-base">Start</button>
      </span>
    : state === 'running' || state === 'paused'
      ? <span className="col-start-2 flex items-center">
        {state === 'running'
          ? <button onClick={() => match.state = 'paused'} className="btn btn-svg text-base"><PauseSVG/></button>
          : <button onClick={() => match.state = 'running'} className="btn btn-svg text-base"><PlaySVG/></button>}
        <button onClick={() => match.state = 'finished'} className="btn text-base">Beenden</button>
      </span>
    : state === 'finished' || editing
      ? <>
        <input onInput={e => leftScore = e.currentTarget.value} className="text-base" type="text" defaultValue={match.leftScore} onFocus={selectAll}/>
        <button onClick={closeMatch} className="btn text-base">Speichern</button>
        <input onInput={e => rightScore = e.currentTarget.value} type="text" className="text-right text-base" defaultValue={match.rightScore} onFocus={selectAll}/>
      </>
      : <>
        <div className="text-base">{leftScore}</div>
        <button onClick={() => setEditing(true)} className="btn text-base">Bearbeiten</button>
        <div className="text-right text-base">{rightScore}</div>
      </>}
  </div>
}

export default RunningMatch

// src/lib/tournament/RunningMatch.svelte
<script lang="ts">
    import EditableText from '$lib/editable/EditableText.svelte'
    import Play from '$lib/svg/Play.svelte'
    import Pause from '$lib/svg/Pause.svelte'
    import {toStore} from '$lib/tournament'
    import {selectedMatch} from '$lib/matches'

    export let match: Match
    export let contestants: Contestants
    export let settings: Settings

    if (match.time === 0 && match.state === 'waiting') 
        match.time = settings.defaultTime
    
    const matchStore = toStore(match)
    const leftName = contestants[match.left].name
    const rightName = contestants[match.right].name

    $: ({state, time} = $matchStore)
    let leftScore = match.leftScore.toString()
    let rightScore = match.rightScore.toString()

    $: match.leftScore = parseInt(leftScore)
    $: match.rightScore = parseInt(rightScore)
    
    $: hours = Math.floor(time / 3600)
    $: minutes = Math.floor(time / 60) - hours * 60
    $: seconds = time - hours * 3600 - minutes * 60

    const saveHours = value => {
        const numeric = parseInt(value)
        const clamped = clamp(numeric, 0, 59)
        settings.defaultTime = match.time = clamped * 3600 + minutes * 60 + seconds
    }
    const saveMinutes = value => {
        const numeric = +value
        const clamped = clamp(numeric, 0, 59)
        settings.defaultTime = match.time = hours * 3600 + clamped * 60 + seconds
    }
    const saveSeconds = value => {
        const numeric = +value
        const clamped = clamp(numeric, 0, 59)
        settings.defaultTime = match.time = hours * 3600 + minutes * 60 + clamped
    }
    const clamp = (value, min, max) => {
        if (value < min) return min
        if (value > max) return max
        return value
    }
    const addZeros = number => {
        if (number >= 0 && number <= 9) return `0${number}`
        return '' + number
    }

    const startMatch = () => {
        match.state = 'running'
        $selectedMatch = ''
    }
    const pauseMatch = () => {
        match.state = 'paused'
    }
    const resumeMatch = () => {
        match.state = 'running'
    }
    const finishMatch = () => {
        match.state = 'finished'
    }
    const closeMatch = () => {
        match.state = 'closed'
    }
</script>

<section class:timeout={state === 'finished' && time === 0} class="running-match">
    <div class="name" title={leftName}>{leftName}</div>
    <div class="timer">
        {#if state === 'waiting'}
            <EditableText load={() => addZeros(hours)} save={saveHours} width="2ch" /> :
            <EditableText load={() => addZeros(minutes)} save={saveMinutes} width="2ch" /> :
            <EditableText load={() => addZeros(seconds)} save={saveSeconds} width="2ch" />
        {:else}
            {addZeros(hours)} : {addZeros(minutes)} : {addZeros(seconds)}
        {/if}
    </div>
    <div class="name right" title={rightName}>{rightName}</div>
    {#if state === 'waiting'}
        <button on:click={startMatch} class="btn center">Start</button>
    {:else if state === 'running' || state === 'paused'}
        <span class="center running">
            {#if state === 'running'}
                <button on:click={pauseMatch} class="btn svg"><Pause/></button>
            {:else}
                <button on:click={resumeMatch} class="btn svg"><Play/></button>
            {/if}
            <button on:click={finishMatch} class="btn">Beenden</button>
        </span>
    {:else if state === 'finished'}
        <input bind:value={leftScore} type="text">
        <button class="btn center" on:click={closeMatch}>Speichern</button>
        <input bind:value={rightScore} class="right" type="text">
    {/if}
</section>

<style>
    .running-match {
        display: grid;
        grid-template-columns: 8ch 8ch 8ch;
        align-items: center;
        font-size: 1.7rem;
        gap: .2rem;
    }
    button {
        font-size: 1.2rem;
    }
    .timer {
        font-size: 1.4rem;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .name {
        white-space: nowrap;
        text-overflow: ellipsis;
        overflow: hidden;
    }
    .right {
        justify-self: right;
        text-align: right;
    }
    .timeout {
        color: hsl(var(--red-clr));
    }
    .center {
        grid-column: 2 / 3;
        justify-self: center;
    }
    .svg {
        width: 1rem;
        height: 1rem;
        margin-right: .5rem;
    }
    .running {
        display: flex;
        align-items: center;
    }
    input {
        width: 3ch;
        font-size: 1.3rem;
    }
</style>
