// src/components/tournament/Tiebreaker.tsx
import {useState, useEffect} from 'react'
import {contestants, state} from '@/state/tournament'

interface TiebreakerProps {
  tiebreaker: App.Tiebreaker,
  heading?: string,
  onSubmit: (selection: App.Id[]) => void
}

const Tiebreaker = ({tiebreaker, heading = 'Tiebreaker', onSubmit}: TiebreakerProps) => {
  const [originalSelection, setOriginalSelection] = useState([...tiebreaker.selection])
  const [selection, setSelection] = useState(originalSelection)
  const diff = tiebreaker.remaining - selection.length
  const prompt = `Es ${diff === 1 ? 'muss' : 'müssen'} ${diff === 0 ? 'keine mehr' : `noch ${diff === 1 ? 'einer' : diff}`} ausgewählt werden.`

  useEffect(() => {
    const originalSelection = [...tiebreaker.selection]
    setOriginalSelection(originalSelection)
  }, [tiebreaker.selection])

  useEffect(() => {
    setSelection(originalSelection)
  }, [originalSelection])

  const toggle = (id: App.Id) => () => {
    const index = selection.indexOf(id)
    if (index === -1)
      return setSelection([...selection, id])
    setSelection([...selection.slice(0, index), ...selection.slice(index + 1)])
  }

  const handleSubmit = () => {
    onSubmit(selection)
    setOriginalSelection([...selection])
  }

  return <div className="card max-w-xl">
    <h3 className="flex items-center gap-3">
      <span className="text-xl">{heading}</span>
      <button onClick={handleSubmit} className="btn" disabled={diff !== 0 || (originalSelection.length !== 0 && originalSelection.every(mid => selection.includes(mid)))}>
        {originalSelection.length === 0 ? 'Bestätigen' : 'Ändern'}
      </button>
    </h3>
    <div className="p-1"/>
    <div>{prompt}</div>
    <div className="p-2"/>
    <div className="flex flex-wrap gap-1">
      {tiebreaker.options.map(id => {
        const {name} = contestants[id]
        const active = selection.includes(id)
        return <button key={id} disabled={diff === 0 && !active || state.phase === 'brackets' || state.phase === 'done'} className={`btn text-overflow max-w-[20ch] ${active ? 'btn-raised' : ''}`} title={name} onClick={toggle(id)}>{name}</button>
      })}
    </div>
  </div>
}

export default Tiebreaker

// src/lib/tournament/Tiebreaker.svelte
<script lang="ts">
    import {createEventDispatcher} from 'svelte'
    import {toStoreKey} from '$lib/tournament';

    export let tiebreaker: Tiebreaker
    export let contestants: Contestants
    export let heading = 'Tiebreaker'

    $: originalSelection = [...tiebreaker.selection]
    $: selection = originalSelection
    $: diff = tiebreaker.remaining - selection.length
    $: prompt = `Es ${diff === 1 ? 'muss' : 'müssen'} ${diff === 0 ? 'keine mehr' : `noch ${diff === 1 ? 'einer' : diff}`} ausgewählt werden.`


    const toggle = (id: string) => () => {
        const index = selection.findIndex(id_ => id === id_)
        if (index === -1)
            return selection = [...selection, id]
        selection = [...selection.slice(0, index), ...selection.slice(index + 1)]
    }

    const dispatch = createEventDispatcher()
    const submit = () => {
        dispatch('submit', selection)
    }
</script>

<section class="card">
    <h3>
        <span>{heading}</span>
        <button class="btn" disabled={diff !== 0 || (originalSelection.length !== 0 && originalSelection.every(mid => selection.includes(mid)))} on:click={submit}>
            {#if originalSelection.length === 0} Bestätigen {:else} Ändern {/if}
        </button>
    </h3>
    <div class="prompt">{prompt}</div>
    <div class="contestants">
        {#each tiebreaker.options as id}
            {@const {name} = contestants[id]}
            {@const active = selection.includes(id)}
            <button class="btn contestant" class:active disabled={diff === 0 && !active} title={name} on:click={toggle(id)}>{name}</button>
        {/each}
    </div>
</section>

<style>
    section {
        margin-bottom: 1rem;
        max-width: 50ch;
    }
    h3 {
        margin: 0;
        display: flex;
        align-items: center;
    }
    h3 span {
        font-size: 1.3rem;
        margin-right: auto;
    }
    .contestants {
        display: flex;
        gap: .3rem;
        flex-wrap: wrap;
    }
    .contestant {
        max-width: 20ch;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
    .prompt {
        margin-block: .5rem;
    }
</style>
