// src/components/input/EditableText.tsx
import {useEffect, useState} from 'react'
import {useDoubleClick, useClickOutside} from '@/utils/hooks'

interface EditableTextProps {
  editing?: boolean,
  disabled?: boolean,
  load: () => string,
  save: (value: string) => boolean,
  style?: React.CSSProperties,
  className?: string
}

const EditableText = ({
  load,
  save,
  editing: _editing = false,
  disabled = false,
  style,
  className = ''
}: EditableTextProps) => {
  const [editing, setEditing] = useState(_editing)
  const spanRef = useDoubleClick(event => {
    if (disabled)
      return
    event.stopPropagation()
    setEditing(true)
  })
  const inputRef = useClickOutside<HTMLInputElement>(() => {
    setEditing(false)
  })

  const handleKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Escape') {
      setEditing(false)
      return
    }
    if (event.key !== 'Enter')
      return
    const value = event.currentTarget.value.trim()
    if (!save(value))
      return
    setEditing(false) 
  }

  useEffect(() => {
    inputRef.current?.select()
  })

  const text = load()

  if (editing)
    return <input
      type="text"
      ref={inputRef}
      style={style}
      lang="de"
      onKeyDown={handleKeyDown}
      defaultValue={text}
    />

  return <span ref={spanRef} title={text} className={`${disabled ? '' : 'cursor-pointer'} ${className}`} onClick={() => {}}>{text}</span>
}

export default EditableText

// src/lib/editable/EditableText.svelte
<script lang="ts">
    import {clickOutside, doubleClick} from '$lib/actions'

    export let save: (value: string) => void
    export let load: () => string
    export let width = 'auto'
    export let editing = false
    export let disabled = false

    let text = load()

    let inputElement: HTMLInputElement
    const handleDoubleClick = () => {
        if (disabled)
            return
        editing = true
    }

    const handleKeyDown = ({key}) => {
        if (key === 'Enter') return saveAndExitEditing()
        if (key !== 'Escape') return

        editing = false
        text = load()
    }

    const saveAndExitEditing = () => {
        editing = false
        save(text)
        setTimeout(() => text = load())
    }

    $: if (editing) {
        inputElement?.select()
    }
</script>

{#if editing}
    <input
            bind:value={text}
            bind:this={inputElement}
            use:clickOutside
            on:clickoutside={saveAndExitEditing}
            on:keydown={handleKeyDown}
            type="text"
            style="width: {width}"
            lang="de"
    />
{:else}
    <span use:doubleClick on:doubleclick={handleDoubleClick}>{text}</span>
{/if}

<style>
    span {
        cursor: pointer;
    }
</style>
